
package org.skyllias.alomatia.filter.hsb;

import java.awt.*;

/** Filter that shifts hue combining the attractions of multiple poles. */

public class CombinedPoleHueFilter extends BasicPoleHueFilter
{
//==============================================================================

  /** Creates a filter that modifies the hue of images by adding the passed
   *  attraction generated by the hues in colourPoles individually.
   *  A pole passed twice has double effect.
   *  A colour with saturation 0 may have unexpected effects over the inner
   *  calculations, since the hue is then indeterministically defined. */

  public CombinedPoleHueFilter(Attraction attraction, Color... colourPoles)
  {
    super(attraction, colourPoles);
  }

//==============================================================================

  /** Applies the attraction to all the poles. */

  @Override
  protected float getNewHue(float hue, float saturation, float brightness)
  {
    float accumulatedShift = 0;
    for (float currentPole : getAllPoles()) accumulatedShift += getAttraction(currentPole, hue);
    return hue - accumulatedShift;
  }

//------------------------------------------------------------------------------

}
