
package org.skyllias.alomatia.filter.hsb.pole;

import org.skyllias.alomatia.filter.hsb.HsbConverter;

/** Converter that shifts hue combining the attractions of multiple poles. */

public class CombinedPoleHueConverter implements HsbConverter
{
  private final AttractionPoles attractionPoles;

//==============================================================================

  /** Creates a filter that modifies the hue of images by adding the passed
   *  attraction generated by the hues in huePoles individually.
   *  A pole passed twice has double effect. */

  public CombinedPoleHueConverter(Attraction attraction, float... huePoles)
  {
    attractionPoles = new AttractionPoles(attraction, huePoles);
  }

//==============================================================================

  /** Applies the attraction to all the poles. */

  @Override
  public float getNewHue(float hue, float saturation, float brightness)
  {
    float accumulatedShift = 0;
    for (float currentPole : attractionPoles.getAllPoles())
    {
      accumulatedShift += attractionPoles.getAttraction(currentPole, hue);
    }
    return hue - accumulatedShift;
  }

//------------------------------------------------------------------------------

}
